services:
  dashboard-absensi-app:
    build: .
    container_name: dashboard-absensi-app
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
